//get zaposleni
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getZaposleni",
  "sid": "fveti40ivupcu7a5mvo2lfcpv1",
  "data" : {
    "pDioNaziva" : "",
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "MBR",
        "direction": "DESC"
      }
    ]
  }
}

//get vrste posla
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getVrstePosla",
  "sid": "fveti40ivupcu7a5mvo2lfcpv1",
  "data" : {
    "pDioNaziva" : "",
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "NAZ_VP",
        "direction": "DESC"
      }
    ]
  }
}
//get OJ
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getOJ",
  "sid": "h0ep3660rtliv0e489m36v4fi0",
  "data" : {
    "pDioNaziva" : "",
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "SIF_OJ",
        "direction": "DESC"
      }
    ]
  }
}

//get Pregled osoba - operatera
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getPregledOperatera",
  "sid": "ltnp1704nqg0ropu020tik3bn4",
  "data" : {
    "pDioNaziva" : "",
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "NAZIV",
        "direction": "ASC"
      }
    ]
  }
}

//get ovl osobe - mj troska
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getOvlOsobeMjTr",
  "sid": "imb2vmpdnjd1nviijkkefr4kj7",
  "data" : {
    "pDioNaziva" : "",
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "NAZIV",
        "direction": "ASC"
      }
    ]
  }
}

//get EVIDENCIJA RADNOG VREMENA ZAGLAVLJA
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getEvRadnogVremenaZag",
  "sid": "4l7u0827q307kipsk2klng9mc0",
  "data" : {
    "pDioNaziva" : "",
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "SIF_STUPCA",
        "direction": "ASC"
      }
    ]
  }
}

//get Opis Vrste HELP ZA
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getOpisVrste",
  "sid": "4l7u0827q307kipsk2klng9mc0",
  "data" : {
    "pDioNaziva" : "",
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "SIFRA",
        "direction": "ASC"
      }
    ]
  }
}