//get zaposleni
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getZaposleni",
  "sid": "fveti40ivupcu7a5mvo2lfcpv1",
  "data" : {
    "pDioNaziva" : "",
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "MBR",
        "direction": "DESC"
      }
    ]
  }
}

//get vrste posla
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getVrstePosla",
  "sid": "fveti40ivupcu7a5mvo2lfcpv1",
  "data" : {
    "pDioNaziva" : "",
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "NAZ_VP",
        "direction": "DESC"
      }
    ]
  }
}
//get OJ
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getOJ",
  "sid": "h0ep3660rtliv0e489m36v4fi0",
  "data" : {
    "pDioNaziva" : "",
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "SIF_OJ",
        "direction": "DESC"
      }
    ]
  }
}

//get Pregled osoba - operatera
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getPregledOperatera",
  "sid": "ltnp1704nqg0ropu020tik3bn4",
  "data" : {
    "pDioNaziva" : "",
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "NAZIV",
        "direction": "ASC"
      }
    ]
  }
}

//get ovl osobe - mj troska
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getOvlOsobeMjTr",
  "sid": "imb2vmpdnjd1nviijkkefr4kj7",
  "data" : {
    "pDioNaziva" : "",
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "NAZIV",
        "direction": "ASC"
      }
    ]
  }
}

//get EVIDENCIJA RADNOG VREMENA ZAGLAVLJA
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getEvRadnogVremenaZag",
  "sid": "17jaacrjhb1o39vl9lhp2cng45",
  "data" : {
    "pDioNaziva" : "",
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "SIF_STUPCA",
        "direction": "ASC"
      }
    ]
  }
}

//get Opis Vrste HELP ZA
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getOpisVrste",
  "sid": "4l7u0827q307kipsk2klng9mc0",
  "data" : {
    "pDioNaziva" : "",
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "SIFRA",
        "direction": "ASC"
      }
    ]
  }
}

//get EVIDENCIJA RADNOG VREMENA ZAGLAVLJA VEZE
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getEvRadnogVremenaZagVeze",
  "sid": "17jaacrjhb1o39vl9lhp2cng45",
  "data" : {
    "pDioNaziva" : "",
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "SIF_STUPCA",
        "direction": "ASC"
      }
    ]
  }
}

//get ŠIFRE kod EVIDENCIJA RADNOG VREMENA ZAGLAVLJA VEZE
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getEvRadnogVremenaZagVezeSifra",
  "sid": "17jaacrjhb1o39vl9lhp2cng45",
  "data" : {
    "pDioNaziva" : "",
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "SIF_STUPCA",
        "direction": "ASC"
      }
    ]
  }
}
//get VRSTE POSLA kod EVIDENCIJA RADNOG VREMENA ZAGLAVLJA VEZE
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getEvRadnogVremenaZagVrIzracuna",
  "sid": "17jaacrjhb1o39vl9lhp2cng45",
  "data" : {
    "pDioNaziva" : "",
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "SIFRA",
        "direction": "ASC"
      }
    ]
  }
}

//get EVIDENCIJA RADNOG VREMENA
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getEvRadnogVremena",
  "sid": "17jaacrjhb1o39vl9lhp2cng45",
  "data" : {
    "pIdKorisnika" : "4",
    "pMbr" : 46,
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "SIFRANAZIV",
        "direction": "ASC"
      }
    ]
  }
}


//PRIPREMA EVIDENCIJE RADNOG VREMENA SVI RADNICI (perSviRnSviRadnici)
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "pripremaGetEvRadnogVremenaSviRadnici",
  "sid": "v582fts4oekk809cq17ha1nap4",
  "data" : {
    "pIdKorisnika" : "15",
    "pSifVlas" : "144",
    "pSifOj" : "%",
    "pZaMjesec" : "12.2024"
  }
}

//get EVIDENCIJA RADNOG VREMENA SVI RADNICI
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getEvRadnogVremenaSviRadnici",
  "sid": "v582fts4oekk809cq17ha1nap4",
  "data" : {
    "pIdKorisnika" : 15,
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "NAZIV_MT",
        "direction": "ASC"
      }
    ]
  }
}

//get EVIDENCIJA RADNOG VREMENA SVI RADNICI HELP OJ
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getEvRadnogVremenaSviRadniciHelpOj",
  "sid": "v582fts4oekk809cq17ha1nap4",
  "data" : {
    "pIdKorisnika" : 15,
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "vrsta",
        "direction": "ASC"
      }
    ]
  }
}

//get KONTROLA FONDA SATI
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getKontrolaFondaSati",
  "sid": "il4soe65ccllm59ovdruhlg3j3",
  "data" : {
    "pDanMjesec": "M",
    "pDatum" : "01.11.2024",
    "pSifOj" : "%",
    "pZaSati" : "184",
    "limit": 10,
    "page": 1
  }
}

//get KONTROLA FONDA SATI HELP OJ
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getKontrolaFondaSatiHelpOj",
  "sid": "il4soe65ccllm59ovdruhlg3j3",
  "data" : {
    "pIdKorisnika" : 15,
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "vrsta",
        "direction": "ASC"
      }
    ]
  }
}

//get Evidencija radnog vremena POMOĆNE LISTE
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getEvRadnogVremenaPomocneListe",
  "sid": "9nrvsdnhi2uff0ind1qmjpp1b6",
  "data" : {
    "pIdKorisnika" : 15,
    "pZaMjesec": "11.2024",
    "pSifMjTr" : "%%%",
    "pMbr" : "1",
    "pSifVp" : "%",
    "limit": 10,
    "page": 1
  }
}

//get GRUPE
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getGrupe",
  "sid": "3cr1fnihmoqhoe3b6ihhvoqii7",
  "data" : {
    "pDioNaziva" : "1",

    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "NAZ_GRUPE",
        "direction": "ASC"
      }
    ]
  }
}

//get POPIS RADNIKA GRUPE
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getPopisRadnikaGrupe",
  "sid": "90946v4aieg1oeq7tn6oepvkm5",
  "data" : {
    "pSifVlas" : 144,
    "pIdOperatera" : 15,
    "pIdGrupe" : 1,
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "NAZIV_RADNIKA",
        "direction": "ASC"
      }
    ]
  }
}



// GET ZAPOSLENI U GRUPI (true false)
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getZaposleniGrupe",
  "sid": "fa2cl58f7b23c4l43ef1dcv8q3",
  "data" : {
    "pDioNaziva" : "",
    "pSifSheme": 2,
    "pIdGrupe" : 4,
    "pIdOperatera" : 4,
    "pSifOj" : "OD107",
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "U_GRUPI",
        "direction": "DESC"
      }
    ]
  }
}

//get POPIS RADNIKA GRUPE
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getPopisRadnikaGrupe",
  "sid": "fa2cl58f7b23c4l43ef1dcv8q3",
  "data" : {
    "pSifVlas" : 144,
    "pIdOperatera" : 4,
    "pIdGrupe" : 4,
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "NAZIV_RADNIKA",
        "direction": "ASC"
      }
    ]
  }
}

//get EVIDENCIJA MJESEČNA
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getEvidencijaMjesecna",
  "sid": "fa2cl58f7b23c4l43ef1dcv8q3",
  "data" : {
    "pIdKorisnika" : 4,
    "pMbr" : "250",
    "pZaMjesec": "01.2025",
    "pSifMjTr": "OD107",
    "pZSifMt": "OD107",
    "pZSifVp": "RRR",
    "limit": 10,
    "page": 2,
    "sort": [
      {
        "property": "D1",
        "direction": "ASC"
      }
    ]
  }
}

//get EVIDENCIJA DNEVNA (SVI RADNICI)
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getEvidencijaDnevna",
  "sid": "fa2cl58f7b23c4l43ef1dcv8q3",
  "data" : {
    "pSifVlas" : 144,
    "pIdKorisnika" : 4,
    "pMbr" : "134",
    "pDatum": "14.01.2025",
    "pZSifMt": "OD107",
    "pZSifVp": "RRR",
    "pSifOj": "OD107",
    "limit": 10,
    "page": 1,
    "sort": [
      {
        "property": "OSOBA, MBR, SIF_VP_N, SIF_MT_N ",
        "direction": "ASC"
      }
    ]
  }
}

// UPDATE ŠIHTERICE DNEVNA EVIDENCIJA
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "upisSihterice",
  "sid": "3fm4n7m60kbak1vmh4r3sik1o1",
  "data" : {
    "pAkcija" : 2,
    "pSifVlas" : 144,
    "pDatum" : "24.01.2025",
    "pMbr" : 318,
    "pSifOj" : "OD109",
    "pSifVP" : "RRR",
    "pSati" : "7",
    "pOd" : "07:01",
    "pDo" : "15:01",
    "pIdOperatera" : 15,
    "RID" : "AAAE8QAAFAAAGckAAG"
  }
}

// GET Prikaza Grupni Unos
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "prikazGrupniUnos",
  "sid": "gcv4lh82skictbgmq5s4k6nrv2",
  "data" : {
    "pIdOperatera" : 4,
    "pZaMjesec" : "01.2025",
    "limit": 100,
    "page": 1
  }
}


// GET Prikaza Grupni Unos
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getSheme",
  "sid": "gcv4lh82skictbgmq5s4k6nrv2",
  "data" : {
    "pDioNaziva": "%%",
    "pSifSheme" : "",
    "limit": 100,
    "page": 1
  }
}


//get rekapitulacija sati mjesečna
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getRekapitulacijaSatiMjesecna",
  "sid": "m49vgbc5vhvsr0flj2qoqhnct3",
  "data" : {
    "pIdKorisnika" : 4,
    "pMbr" : "239",
    "pZaMjesec": "02.2025",
    "pSifMjTr": "%",
    "pZSifMt": "%",
    "pZSifVp": "%"
  }
}

//get rekapitulacija sati dnevna
###
POST http://192.168.88.169:8080/php_angularAPI_oracle_sihterica/router.php
Content-Type: application/json

{
  "action" : "Sihterica",
  "method" : "getRekapitulacijaSatiDnevna",
  "sid": "busmeh9ti014pd8fjobmvgb183",
  "data" : {
    "pSifVlas" : 144,
    "pIdKorisnika" : 4,
    "pMbr" : "%",
    "pDatum": "13.02.2025",
    "pZSifMt": "%",
    "pZSifVp": "%",
    "pSifOj": "%"
  }
}